server:
  port: 8888

#spring:

graphql.servlet.mapping: /gql
graphql.servlet.enabled: true
graphql.servlet.corsEnabled: false

#GraphiQL
graphiql.mapping: /graphiql
graphiql.endpoint.graphql: /gql
graphiql.enabled: true

